### ISSUE TITLE
Can't install: "ImportError: No module named setuptools"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [VitaliyRodnenko/geeknote#185]
$ python setup.py install

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by meenakshykurup** [comment]
i do have the same issue .
Reading package lists... Done
Building dependency tree

Reading state information... Done
E: Unable to locate package setuptools
