### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by benmichaelfrench** [VitaliyRodnenko/geeknote#257]
get the following error when using debian wheezy 7.7

: Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 893, in main
    Notes().create(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 637, in create
    inputData = self._parseInput(title, content, tags, notebook, resource)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 705, in _parseInput
    "resources": resources if resources else [],
NameError: global name 'resources' is not defined

**Comment by jeffkowalski** [comment]
Likely due to a bad merge on that branch.
See comments in https://github.com/VitaliyRodnenko/geeknote/pull/258

**Comment by adarrra** [comment]
Please, for newbi-user - how to fix this error?

**Comment by arrygoo** [comment]
Hey @adarrra. I Just downloaded this and had the two following errors that @benmichaelfrench mentioned. 
```ShellSession
MacBook-Pro:geeknote arry$ sudo geeknote create --title mytitle --content myContent --notebook myNotebook --tags myTag
>>> : Connect to Evernote...Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 893, in main
    Notes().create(**ARGS)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 637, in create
    inputData = self._parseInput(title, content, tags, notebook, resource)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 705, in _parseInput
    "resources": resources if resources else [],
NameError: global name 'resources' is not defined
```
and the second one appears after fixing the first one.
```ShellSession
MacBook-Pro:geeknote arry$ sudo geeknote edit myTitle
  > : Connect to Evernote...Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 896, in main
    Notes().edit(**ARGS)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 655, in edit
    inputData = self._parseInput(title, content, tags, notebook, resource, note)
TypeError: _parseInput() takes at most 6 arguments (7 given)
```
I'm not at all familiar with the code. But my quick fix to get it working was to comment out those two lines. 
comment out line 705 by adding a #into the begging of the file
So: 
'python
699     def _parseInput(self, title=None, content=None, tags=None, notebook=None, note=None):
700         result = {
701             "title": title,
702             "content": content,
703             "tags": tags,
704             "notebook": notebook,
<b>705             "resources": resources if resources else [],</b>
706         }
707         result = tools.strip(result)
`
Change it to
`
699     def _parseInput(self, title=None, content=None, tags=None, notebook=None, note=None):
700         result = {
701             "title": title,
702             "content": content,
703             "tags": tags,
704             "notebook": notebook,
<b>705             #"resources": resources if resources else [],</b>
706         }
707         result = tools.strip(result)
```

And 
 
```python

655         inputData = self._parseInput(title, content, tags, notebook,
``` 
** resource **
python```
, note) 
```
to 
655         inputData = self._parseInput(title, content, tags, notebook, note)
```
</pre>

Then save and you should be good. I hope this doesn't break too many things. But looking through evernote api I couldn't even find the use of "resource".

**Comment by jeffkowalski** [comment]
@adarrra a , @arrygoo : the errors you're encountering are due to a bad merge in this branch, which only partially brought in support for "resources".  Resources is another name for attachments, which can be uploaded along with a note. 
There are other branches in github which properly support resources and don't have any of the syntax or runtime errors you're experiencing.  To see those branches, click on the number to the right of the word "fork" at the top right of the github page for this repository.

The branch I've been maintaining is on example that works.  
You can download it here: https://github.com/jeffkowalski/geeknote/archive/master.zip
and see it here: https://github.com/jeffkowalski/geeknote

It is probably unwise to make other versions that comment out the resources line.  That's not the right fix.

**Comment by unsover** [comment]
Hey @jeffkowalski I tried cloning your repo, but it is also not working, having the same error.  Just fyi, using python 2.7 on a Mac.

**Comment by VitaliyRodnenko** [comment]
Hello. I've fixed that, try it again please.
https://github.com/VitaliyRodnenko/geeknote/pull/258

**Comment by adarrra** [comment]
now everything works! thanx a lot! cool app
