### ISSUE TITLE
What happens when I type my password?

### ISSUE THREAD

**Issue by saroele** [VitaliyRodnenko/geeknote#273]
Hi,

I want to give geeknote a try, but I could not find any doc on how save it is to enter my evernote password.  Can someone explain me what happens to my password?  Is it stored on a geeknote server?

thanks

**Comment by weakish** [comment]
> Can someone explain me what happens to my password? Is it stored on a geeknote server?

No. Geeknote use your username and password to get access token from evernote.com.

And that token is stored in `~/.geeknote/database.db`.

For more information, google `oauth`.

**Comment by saroele** [comment]
ok, thanks for the info!
