### ISSUE TITLE
incorrect login or password

### ISSUE THREAD

**Issue by wenlibin** [VitaliyRodnenko/geeknote#275]
Hello, 

I install the geeknote. And run `geeknote login' to login using yinxiang.com account but failed. 

Login: xxx@gmail.com             
Password: 
Sorry, incorrect login or password      

I am sure that I enter the right password. Any problem there?

**Comment by alswl** [comment]
+1

**Comment by wenlibin** [comment]
I got it. In file: ./geeknote/config.py, use the following things instead, 
    USER_BASE_URL = "app.yinxiang.com"
    USER_STORE_URI = "https://app.yinxiang.com/edam/user"

**Comment by blurm** [comment]
Really helped! Thanks
